version: '3.5'

services:
  appointmentscheduler:
    build:
      context: ../../
      dockerfile: aws/dev/Dockerfile
    volumes:
      - /app/node_modules
      - ../../:/app
    ports:
      - "3000:3000"
